### ISSUE TITLE
Revisión

### ISSUE THREAD

**Issue by EduardoHernandezGuzman** [4GeeksAcademy/Meryalvhe-GeneradorDeDominios#1]
# Revisión - Aprobado :white_check_mark:
- [x] Estilo de código y limpieza
# Feedback
- ¡Bien hecho @Meryalvhe ... ¡Felicidades por este proyecto!
## Estilo de código y limpieza
- ¡Buen trabajo!
## Mejores prácticas/comentarios
- Muy bien resuelto.
- Genial que hayas usado tres formas diferentes de resolverlo.

**Comment by Meryalvhe** [comment]
### Gracias @EduardoHernandezGuzman 👍
